name: JUCE CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Get scoop
        if: steps.juce-cache.outputs.cache-hit != 'true'
        run: |
          $env:SCOOP='D:\a\NewProject\NewProject\scoop'
          [environment]::setEnvironmentVariable('SCOOP',$env:SCOOP,'User')
          iwr -useb get.scoop.sh | iex
          scoop install wget unzip make
      - name: Get JUCE
        if: steps.juce-cache.outputs.cache-hit != 'true'
        run: |
          D:\a\NewProject\NewProject\scoop\apps\wget\current\wget https://github.com/juce-framework/JUCE/releases/download/6.0.1/juce-6.0.1-windows.zip
          unzip juce-6.0.1-windows.zip
      - name: Cache JUCE & scoop
        id: juce-cache
        uses: actions/cache@v2
        with:
          path: |
            D:\a\NewProject\NewProject\JUCE\*
            D:\a\NewProject\NewProject\scoop\*
          key: ${{ runner.os }}-juce
      - name: Build
        run: |
          cd .\Builds\LinuxMakefile
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Output
          path: .\Builds\LinuxMakefile\build\
